# Generated by Django 4.2.11 on 2026-04-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_user_id_1ab870_idx',
            old_name='notes_note_user_id_9520f6_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_user_id_3ab1c3_idx',
            old_name='notes_note_user_id_008479_idx',
        ),
    ]
